// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
	async invalidateShadow(): Promise<Result<null, string>> {
		try {
			return {
				status: "ok",
				data: await TAURI_INVOKE("invalidate_shadow"),
			};
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: "error", error: e as any };
		}
	},
	async addTasks(filePaths: string[]): Promise<Result<null, string>> {
		try {
			return {
				status: "ok",
				data: await TAURI_INVOKE("add_tasks", { filePaths }),
			};
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: "error", error: e as any };
		}
	},
	async getTasks(
		kind: MediaKind | null,
		start: number,
		limit: number,
	): Promise<Result<ConversionTask[], string>> {
		try {
			return {
				status: "ok",
				data: await TAURI_INVOKE("get_tasks", { kind, start, limit }),
			};
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: "error", error: e as any };
		}
	},
	async addMockTasks(count: number): Promise<Result<null, string>> {
		try {
			return {
				status: "ok",
				data: await TAURI_INVOKE("add_mock_tasks", { count }),
			};
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: "error", error: e as any };
		}
	},
};

/** user-defined events **/

/** user-defined constants **/

/** user-defined types **/

export type AudioConversionOptions = {
	/**
	 * Target audio codec (e.g., "mp3", "opus", "flac", "copy").
	 */
	audioCodec: string | null;
	/**
	 * Target audio bitrate (e.g., "192k", "320k") or quality level.
	 */
	audioQuality: string | null;
	/**
	 * Sample rate (e.g., 44100, 48000).
	 */
	sampleRate: number | null;
};
export type ConversionOptions =
	| { type: "video"; data: VideoConversionOptions }
	| { type: "image"; data: ImageConversionOptions }
	| { type: "audio"; data: AudioConversionOptions }
	| { type: "document"; data: DocumentConversionOptions };
export type ConversionTask = {
	id: string;
	kind: MediaKind;
	inputPath: string;
	outputPath: string | null;
	sourceFormatOverride: FileFormat | null;
	targetFormat: FileFormat;
	options: ConversionOptions | null;
};
export type DocumentConversionOptions = {
	/**
	 * For PDF output: restrict permissions.
	 */
	pdfPermissions: PdfPermissions | null;
	/**
	 * For text output: line wrapping width.
	 */
	lineWrap: number | null;
};
export type FileFormat =
	| "Mp4"
	| "Webm"
	| "Gif"
	| "Avi"
	| "Mkv"
	| "Wmv"
	| "Mov"
	| "Mts"
	| "Flv"
	| "Ogv"
	| "Mp3"
	| "Wav"
	| "Flac"
	| "Ogg"
	| "Aac"
	| "M4a"
	| "Opus"
	| "Jpg"
	| "Jpeg"
	| "Png"
	| "Webp"
	| "Bmp"
	| "Tiff"
	| "Avif"
	| "Ico"
	| "Pdf"
	| "Docx"
	| "Odt"
	| "Txt"
	| "Html"
	| "Md"
	| "Epub";
export type ImageConversionOptions = {
	/**
	 * Target quality (e.g., 1-100 for lossy formats like JPG/WebP).
	 */
	quality: number | null;
	/**
	 * Optional resizing parameters.
	 */
	resize: ResizeOptions | null;
	/**
	 * Format-specific: PNG compression level (0-9).
	 */
	pngCompression: number | null;
	/**
	 * Format-specific: WebP lossless encoding.
	 */
	webpLossless: boolean | null;
};
export type MediaKind = "Video" | "Audio" | "Image" | "Document";
export type PdfPermissions = {
	allowPrinting: boolean;
	allowCopying: boolean;
	allowEditing: boolean;
};
export type ResizeMode = "stretch" | "fit" | "fill";
export type ResizeOptions = {
	width: number | null;
	height: number | null;
	/**
	 * How to handle aspect ratio ("stretch", "fit", "fill"). Default should be "fit".
	 */
	mode: ResizeMode | null;
	/**
	 * Filter type for resizing (e.g., "lanczos3", "nearest").
	 */
	filter: string | null;
};
export type VideoConversionOptions = {
	/**
	 * Encoding speed preset (e.g., "medium", "fast", "slow"). Specific values depend on codec.
	 */
	speedPreset: string | null;
	/**
	 * Constant Rate Factor (lower means better quality, larger file). Specific range depends on codec.
	 */
	crf: number | null;
	/**
	 * Target video codec (e.g., "libx264", "libx265", "av1", "copy"). None leaves it to the converter.
	 */
	videoCodec: string | null;
	/**
	 * Target audio codec (e.g., "aac", "opus", "copy"). None leaves it to the converter.
	 */
	audioCodec: string | null;
	/**
	 * Target audio bitrate (e.g., "192k").
	 */
	audioBitrate: string | null;
};

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) =>
									TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) =>
									TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) =>
									TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
